### ISSUE TITLE
ナビゲーションのリンク部分

### ISSUE THREAD

**Issue by shiori-yasutani** [shiori-yasutani/bokurahatensai#4]
- [x] 下線が消えない
- [x] 色を変えられない

**Comment by shiori-yasutani** [comment]
@masatakashida 
知ってたら教えてください

<img width="1186" alt="2018-12-22 15 27 22" src="https://user-images.githubusercontent.com/34346704/50371434-417c2d80-05fe-11e9-8fbd-7fb95f8d403c.png">
<img width="1161" alt="2018-12-22 15 27 38" src="https://user-images.githubusercontent.com/34346704/50371435-417c2d80-05fe-11e9-8710-db49c58d1120.png">

**Comment by masatakashida** [comment]
できてたので、閉じますね。
